spring:
  application:
    name: doctorat-portal

  datasource:
    url: jdbc:mysql://localhost:3306/db_doctorat?createDatabaseIfNotExist=true
    username: root
    password: Roles1234@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8080

# Ajout du mode DEBUG pour voir l'erreur de connexion précise
logging:
  level:
    org:
      springframework:
        security: DEBUG
